steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'terraform work'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        cd terrafrom
        echo "***************************"
        echo "       terraform init"
        echo "***************************"
        terraform init
        echo "***************************"
        echo "       terraform plan"
        echo "***************************"
        terraform plan
        echo "***************************"
        echo "       terraform apply"
        echo "***************************"
        terraform apply -auto-approve