steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'tf start'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        pwd
        ls
        cd terrafrom
        pwd
        terraform init
        terraform plan
        terraform apply -auto-approve
    options:
         logging: CLOUD_LOGGING_ONLY
  # [START tf-plan]
  #/- id: 'tf plan'
  #  name: 'hashicorp/terraform:1.0.0'
  #  entrypoint: 'sh'
  #  args:
  #  - '-c'
  #  - |
  #      terraform plan

  # [END tf-plan]

  # [START tf-apply]
  #- id: 'tf apply'
  #  name: 'hashicorp/terraform:1.0.0'
  #  entrypoint: 'sh'
  #  args:
  #  - '-c'
  #  - |
   #     terraform apply -auto-approve