steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'tf start'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        pwd
        ls
        cd terrafrom
        pwd
        terraform init
        terraform plan
        terraform apply -auto-approve
  - id: Permissiosn add
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: sh
    args:
      - '-c'
      - |
          gcloud functions add-iam-policy-binding visitor-count-2 --member=allUsers --role=roles/cloudfunctions.invoker

  # [START tf-plan]
  #/- id: 'tf plan'
  #  name: 'hashicorp/terraform:1.0.0'
  #  entrypoint: 'sh'
  #  args:
  #  - '-c'
  #  - |
  #      terraform plan

  # [END tf-plan]

  # [START tf-apply]
  #- id: 'tf apply'
  #  name: 'hashicorp/terraform:1.0.0'
  #  entrypoint: 'sh'
  #  args:
  #  - '-c'
  #  - |
   #     terraform apply -auto-approve